#!/usr/bin/env tsx
import { FileDatabase } from "../../../../../shared/src/database.js";
import { writeText } from "../../../../../shared/src/utils.js";
import path from "node:path";
import fs from "node:fs/promises";

const args = process.argv.slice(2);
const slug = args.find(a => a.startsWith("--slug="))?.split("=")[1];

if (!slug) {
  console.error("Usage: tsx generate.ts --slug=<slug>");
  process.exit(1);
}

const db = new FileDatabase();

async function run() {
  const actors = await db.listActors();
  const actor = actors.find(a => a.slug === slug);
  if (!actor) {
    throw new Error(`Actor not found in database: ${slug}`);
  }

  // We construct templates based on the metadata in actor
  const actorDir = actor.actorDir || path.resolve(process.cwd(), "generated-actors", slug);
  
  console.log(`Generating documentation files for ${slug} under ${actorDir}...`);
  
  const readmeContent = `# ${actor.name}

## What It Does
This Actor is generated by the Creator Factory Main Agent to run workflow automations.

## How It Works
1. Validates input properties.
2. Runs the target workflow script.
3. Pushes extracted data to the default Apify dataset.

## Inputs
- query: plain text request or target URL.
- maxItems: limit of records to extract.
- includeEnrichment: applies heuristic analysis.

## Output Fields
- title
- sourceUrl
- data
- confidence
- capturedAt
`;

  await fs.mkdir(path.join(actorDir, ".actor"), { recursive: true });
  await writeText(path.join(actorDir, "README.md"), readmeContent);
  await writeText(path.join(actorDir, ".actor", "README.md"), readmeContent);
  await writeText(path.join(actorDir, "CHANGELOG.md"), `# Changelog\n\n## 0.1.0\n- Initial generated Actor.\n`);
  await writeText(path.join(actorDir, ".actor", "CHANGELOG.md"), `# Changelog\n\n## 0.1.0\n- Initial generated Actor.\n`);
  await writeText(path.join(actorDir, "ACTOR.md"), `# ${actor.name}\n\nRunning workflow for: ${actor.slug}\n`);
  await writeText(path.join(actorDir, "EXAMPLES.md"), `# Examples\n\n\`\`\`json\n{"query":"example","maxItems":10}\n\`\`\`\n`);

  console.log("Documentation generated successfully.");
}

run().catch(err => {
  console.error("Documentation generation failed:", err);
  process.exit(1);
});
